### ISSUE TITLE
2017-10-25 to do

### ISSUE THREAD

**Issue by l-d-s** [d-cameron/sv_benchmark#4]
In `roc_by`:

-   ~~Caller colors the same for each caller~~
-   ~~Callers listed alphabetically in ROC by plots~~
-   ~~Symbols rather than colors (or: starting letter)~~ (make symbol baubles optional?)
-   ~~-> all in a metadata df~~
-   ~~Lines a bit thinner?~~
-   ~~Check fig 1 for red/green~~ (need to do across other truth sets)
-   ~~Open circle & black text for "PASS ONLY" baubles?~~

Simulation plot:

-   Remove read lengths below 75bp?
-   Idea: "range of sensitivity >10%" plot.

Figure 3

-   ~~Only have 1 bar for callers that don't have a "PASS" subset~~
-   ~~Callers listed alphabetically~~
-   ~~Put truth in brackets~~

Figure 4

-   ~~Figure 4 change heights~~

All plots:

-   Callers listed alphabetically

~~Write out ROC by event size by repeat type (supp)~~ Should appear on regen

Figure 5

-    ~~Cortex over-labelling for NA12878 set 3~~ Should appear on regen

Manuscript:

-    Check citation for shared calls plots
-    Also note smarter ensemble options

**Comment by d-cameron** [comment]
Issues with colours
- need fixed colour for each caller
- callers listed alphabetically (move gridss to middle; just change the arg in the factor conversion)
- change circle at end to symbol
- make sure similar callers have different colours (esp hydra/breakdancer)
- 3 data sets on the same panel

Figure 1:
	- 3 panels: na12878, CHM1, CHM13
	- suppfig: all 4 NA12878 ROCS

Figure 2:
	- Remove <50bp calls
	- Pretty colours
	- Just rl=100
- pull it?

Figure 3:
	- some sort of ensemble plot here
	- Match caller sort order
	- add ensemble calling
		- reduce shape/colour to {1,2,3+} callers of {1,2,3,4+} callers
	- bracket the truth [Parikh et al]

Figure 4:
	- change heights
	- Change order of repeat labels (easy first; hard last)
	- Drop hydra from by event size panel
	Supp: write out roc by event size vs repeat type

Figure 5:
	- cortex labelling is overplotted

**Comment by l-d-s** [comment]
-   ~~Repeat order: No repeat, SINE, LINE, DNA, LTR, SImple/Tandem, Low complexity, Other~~
-   ~~Strip Hydra out of precision-recall by event size plot~~

**Comment by l-d-s** [comment]
-   ~~Resolve selection of ensemble plots. Implement TP suggestions.~~

**Comment by l-d-s** [comment]
-   ~~Double-check 5 or fewer plots~~

**Comment by l-d-s** [comment]
-   Check non-DEL figure 3s for bar color issues.
