### ISSUE TITLE
Acronym O.E.A.

### ISSUE THREAD

**Issue by DarioS** [d-cameron/sv_benchmark#7]
What does O.E.A. in Supplementary Table 1 stand for? The full words are not in the journal article nor in its supplementary material.

**Comment by d-cameron** [comment]
One-end anchored read pairs. That is, read pairs in which only one of the two are mapped. Unfortunately, there's no consensus in the literature about what to call these. During drafting I remove the acronym from the manuscript body as it's not a well-known one but it appears I didn't also update the supplementary column header.
